"""createtable2

Revision ID: 6033cf34daf0
Revises: 831877329576
Create Date: 2024-01-09 15:54:45.428793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6033cf34daf0'
down_revision = '831877329576'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', sa.String(), nullable=True))
    op.add_column('admin', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('admin', sa.Column('email', sa.String(), nullable=True))
    op.add_column('admin', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_column('admin', 'name')
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.add_column('admin', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('admin', 'hashed_password')
    op.drop_column('admin', 'email')
    op.drop_column('admin', 'full_name')
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###
