"""createtable

Revision ID: 831877329576
Revises: 
Create Date: 2024-01-09 15:37:39.835900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831877329576'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
